### ISSUE TITLE
FlowRouter support?

### ISSUE THREAD

**Issue by derwaldgeist** [chriswessels/meteor-back-behaviour#1]
This package sounds very interesting, but I am using FlowRouter. Are you planning to support this router as well?

**Comment by chriswessels** [comment]
@derwaldgeist Yes, but this may take some time for me to get to.

PRs welcome!

**Comment by derwaldgeist** [comment]
Thanks for your reply!

**Comment by joelpickup** [comment]
👍

**Comment by chriswessels** [comment]
I've published `1.0.0` to Atmosphere that includes Flow Router support. Please see README.
